export default {
  details: 'Details',
  home: 'Home',
  settings: 'Settings',

  welcome: 'Welcome to CoinChums!',
  welcomeTitle: 'With CoinChums, Track balances effortlessly among friends or groups',
  next: 'Next',
  addExpense: 'Add an expense',
  change_language: 'Change Language',
  terms: 'Terms & Condition',
  detailsNavigation: 'Go to details',
  clickMe: 'Click Me',
  env: 'Accessing env example',
  err: 'Something Went Wrong!',
  try: 'Try Again',
  profile: 'Profile',
  footer: 'Footer',
  accExample: 'This is the example usage of the Accordion Component.',
  signUp: 'Sign Up',
  login: 'Log in',
};
