export default {
  details: 'Details',
  home: 'Home',
  settings: 'Settings',

  welcome: 'Welcome to CoinChums!',
  welcomeTitle: 'With CoinChums, Track balances effortlessly among friends or groups',
  next: 'Next',
  addExpense: 'Add an expense',
  change_language: 'Switch Language',
  terms: 'Terms & Condition',
  detailsNavigation: 'Go to details',
  clickMe: 'Click Me',
  env: 'Accessing env example',
  err: 'Something Went Wrong!',
  try: 'Try Again',
  profile: 'Profile',
  footer: 'Footer',
  accExample: 'This is the example usage of the Accordion Component.',
  signUp: 'Sign Up',
  login: 'Log in',
  noExpense: 'no expenses',
  owe: 'you owe',
  owes: 'you are owed',
  groupCreation: 'Create a group',
  groupName: 'Group name',
  languages: 'Languages',
  logout: 'Logout',
  groupDesc: 'Group description',
  create: 'Create Group',
};
