export default {
  details: 'विवरण',
  home: 'होम',
  settings: 'सेटिंग्स',

  welcome: 'कॉइनचम्स में आपका स्वागत है!',
  welcomeTitle: 'कॉइनचम्स के साथ, दोस्तों या समूहों के बीच सरलता से शेष राशियों का ट्रैक करें',
  next: 'आगे',
  addExpense: 'व्यय जोड़ें',
  change_language: 'भाषा बदलें',
  terms: 'शर्तें और शर्तें',
  detailsNavigation: 'विवरण पर जाएं',
  clickMe: 'मुझ पर क्लिक करो',
  env: 'Env उदाहरण तक पहुंच रहा है',
  err: 'कुछ गड़बड़ हो गई है!',
  try: 'पुनः प्रयास करें',
  profile: 'प्रोफाइल',
  footer: 'फ़ूटर',
  accExample: 'यह एक्कॉर्डियन कॉम्पोनेंट के उदाहरण का उपयोग है।',
  signUp: 'साइन अप करें',
  login: 'लॉग इन करें',
  noExpense: 'खर्च नहीं',
  owe: 'तुम ऋणी हो',
  owes: 'तुम्हें ऋण दिया गया है',
  groupCreation: 'ग्रुप बनाएं',
  groupName: 'समूह का नाम',
  languages: 'भाषाओं',
  logout: 'लॉगआउट',
};
