name: CoinChums CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./node_modules
            ./yarn.lock
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build Android Release
        run: |
          cd android && ./gradlew --daemon assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
