name: CoinChums CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install npm dependencies
        run: npm install

      - name: Configure Google Sign-In with webClientId
        run: |
          echo "GoogleSignin.configure({ webClientId: '${{ secrets.WEB_CLIENT_ID }}', offlineAccess: true })" > google-signin-config.js
        env:
          WEB_CLIENT_ID: ${{ secrets.WEB_CLIENT_ID }}

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
